# Generated by Django 5.0.9 on 2024-10-18 20:21

from django.db import migrations, models

import hyperlink

def get_endpoint_full_path(endpoint):
    try:
        if endpoint.host:
            dummy_scheme = "dummy-scheme"  # workaround for https://github.com/python-hyper/hyperlink/blob/b8c9152cd826bbe8e6cc125648f3738235019705/src/hyperlink/_url.py#L988
            url = hyperlink.EncodedURL(
                scheme=endpoint.protocol or dummy_scheme,
                userinfo=endpoint.userinfo or "",
                host=endpoint.host,
                port=endpoint.port,
                path=tuple(endpoint.path.split("/")) if endpoint.path else (),
                query=tuple(
                    (
                        qe.split("=", 1)
                        if "=" in qe
                        else (qe, None)
                    )
                    for qe in endpoint.query.split("&")
                ) if endpoint.query else (),  # inspired by https://github.com/python-hyper/hyperlink/blob/b8c9152cd826bbe8e6cc125648f3738235019705/src/hyperlink/_url.py#L1427
                fragment=endpoint.fragment or "",
            )
            # Return a normalized version of the URL to avoid differences where there shouldn't be any difference.
            # Example: https://google.com and https://google.com:443
            normalize_path = endpoint.path  # it used to add '/' at the end of host
            clean_url = url.normalize(scheme=True, host=True, path=normalize_path, query=True, fragment=True, userinfo=True, percents=True).to_uri().to_text()
            if not endpoint.protocol:
                if clean_url[:len(dummy_scheme) + 3] == (dummy_scheme + "://"):
                    clean_url = clean_url[len(dummy_scheme) + 3:]
                else:
                    msg = "hyperlink lib did not create URL as was expected"
                    raise ValueError(msg)
            return clean_url
        msg = "Missing host"
        raise ValueError(msg)
    except:
        url = ""
        if endpoint.protocol:
            url += f"{endpoint.protocol}://"
        if endpoint.userinfo:
            url += f"{endpoint.userinfo}@"
        if endpoint.host:
            url += endpoint.host
        if endpoint.port:
            url += f":{endpoint.port}"
        if endpoint.path:
            url += "{}{}".format("/" if endpoint.path[0] != "/" else "", endpoint.path)
        if endpoint.query:
            url += f"?{endpoint.query}"
        if endpoint.fragment:
            url += f"#{endpoint.fragment}"
        return url

def update_endpoint_full_paths(apps, schema_editor):
    EndpointModel = apps.get_model('dojo', 'Endpoint')

    for endpoint in EndpointModel.objects.all():
        endpoint.full_path = get_endpoint_full_path(endpoint)
        endpoint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0217_jira_project_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='full_path',
            field=models.CharField(blank=True, editable=False, help_text='(readonly) The full path of this endpoint, combining protocol, userinfo, host, etc.', max_length=2020, null=True),
        ),
        migrations.RunPython(update_endpoint_full_paths, migrations.RunPython.noop),
    ]
